// Generated by CoffeeScript 1.6.3
(function() {
  YUI().use('node-base', 'node-event-delegate', function(Y) {
    var menuButton, nav;
    Y.one('body').delegate('click', function(e) {
      return e.preventDefault();
    }, 'a[href="#"]');
    menuButton = Y.one('.nav-menu-button');
    nav = Y.one('#nav');
    return menuButton.on('click', function(e) {
      return nav.toggleClass('active');
    });
  });

}).call(this);
