// Generated by CoffeeScript 1.6.3
(function() {
  YUI().use('node-base', 'node-event-delegate', 'app-base', 'app-transitions', 'handelbars', 'menuplugin', function(Y) {
    var pageApp;
    Y.one('body').delegate('click', function(e) {
      return e.preventDefault();
    }, 'a[href="#"]');
    pageApp = new Y.App({
      views: {
        home: {
          preserve: true
        },
        campaigns: {
          parent: 'home'
        },
        players: {
          parent: 'home'
        },
        npcs: {
          parent: 'home'
        },
        encounters: {
          parent: 'home'
        },
        notes: {
          parent: 'home'
        },
        external: {
          parent: 'home'
        },
        about: {
          parent: 'home'
        }
      },
      transitions: true,
      container: '#pageContent',
      serverRouting: false
    });
    pageApp.route('*', function() {});
    Y.menuplugin.render();
    return pageApp.render().dispatch();
  });

}).call(this);
